# Generated by Django 3.2.3 on 2021-05-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('nom', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
