# Generated by Django 3.2.3 on 2021-05-26 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaceManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Missio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('descripcio', models.CharField(max_length=200)),
                ('data_finalitzacio', models.DateTimeField()),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='spaceManager.agencia')),
            ],
        ),
    ]
