# Generated by Django 3.2.3 on 2021-06-07 18:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spaceManager', '0002_auto_20210526_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missio',
            name='data_finalitzacio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Nau',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('capacitat', models.IntegerField()),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='spaceManager.agencia')),
            ],
        ),
    ]
