# Generated by Django 3.2.3 on 2021-06-07 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaceManager', '0003_auto_20210607_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('nom', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='spaceManager.agencia')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='spaceManager.pais')),
            ],
        ),
    ]
