# Generated by Django 3.2.3 on 2021-06-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceManager', '0005_astronauta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronauta',
            name='genere',
            field=models.CharField(choices=[('H', 'h'), ('D', 'Mrs.'), ('?', '?')], max_length=1),
        ),
    ]
