# Generated by Django 3.2.3 on 2021-06-09 12:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spaceManager', '0008_auto_20210609_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Llancament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_llancament', models.DateTimeField(default=django.utils.timezone.now)),
                ('missio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaceManager.missio')),
                ('nau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaceManager.nau')),
                ('platafora', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='spaceManager.plataforma')),
            ],
        ),
        migrations.AddField(
            model_name='missio',
            name='naus',
            field=models.ManyToManyField(through='spaceManager.Llancament', to='spaceManager.Nau'),
        ),
        migrations.AddField(
            model_name='nau',
            name='missions',
            field=models.ManyToManyField(through='spaceManager.Llancament', to='spaceManager.Missio'),
        ),
    ]
