# Generated by Django 3.2.3 on 2021-06-09 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaceManager', '0009_auto_20210609_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='llancament',
            old_name='platafora',
            new_name='plataforma',
        ),
    ]
