# Generated by Django 3.2.3 on 2021-06-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceManager', '0011_auto_20210610_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencia',
            name='astronautes',
        ),
        migrations.RemoveField(
            model_name='astronauta',
            name='llancaments',
        ),
        migrations.AlterField(
            model_name='llancament',
            name='astronautes',
            field=models.ManyToManyField(related_name='astronautes', to='spaceManager.Astronauta'),
        ),
    ]
