# Generated by Django 3.2.3 on 2021-06-10 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaceManager', '0013_alter_llancament_astronautes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronauta',
            name='agencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaceManager.agencia'),
        ),
        migrations.AlterField(
            model_name='astronauta',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaceManager.pais'),
        ),
        migrations.AlterField(
            model_name='llancament',
            name='plataforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaceManager.plataforma'),
        ),
        migrations.AlterField(
            model_name='missio',
            name='agencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaceManager.agencia'),
        ),
        migrations.AlterField(
            model_name='nau',
            name='agencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaceManager.agencia'),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='agencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaceManager.agencia'),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaceManager.pais'),
        ),
    ]
