# Generated by Django 3.2.3 on 2021-06-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceManager', '0016_alter_pais_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nau',
            name='id',
            field=models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False),
        ),
    ]
